export const JobListsDatas = [
  {
    id: "1ed",
    city: "Sydney",
    country: "Australia",
    category: "Internship",
    months: 6,
    school: "ESC Pau",
    company: "Pitcher Partners",
    manager: "Agnès Castaigns",
    cover: "src/IMAGES/sydney2.jpeg",
  },
  {
    id: "2ed",
    city: "London",
    country: "United Kingdom",
    category: "Internship",
    months: 4,
    school: "IAE PAU BAYONNE",
    company: "Xerox",
    manager: "Valérie Thomassin",
    cover: "src/IMAGES/london.jpeg",
  },
  {
    id: "3ed",
    city: "Biarritz",
    country: "France",
    category: "Internship",
    months: 6,
    school: "IAE PAU BAYONNE",
    company: "X-Treme Distribution",
    manager: "Morgan Paul",
    cover: "src/IMAGES/lacsaintjean.jpeg",
  },
  {
    id: "4ed",
    city: "Biarritz",
    country: "France",
    category: "Job",
    months: 48,
    school: "",
    company: "X-Treme Distribution",
    manager: "Morgan Paul",
    cover: "src/IMAGES/lacsaintjean.jpeg",
  },
  {
    id: "5ed",
    city: "Bayonne",
    country: "France",
    category: "Job",
    months: 48,
    school: "",
    company: "Gesadour",
    manager: "Jean Paul Guesnet",
    cover: "src/IMAGES/lacsaintjean.jpeg",
  },
];
